### ISSUE TITLE
Found issues

### ISSUE THREAD

**Issue by aneeshsinghmacquarie** [cftp/aggregator#14]
hi @philipjohn,

As discussed during our call the other day.

I have attached all the issues the we are facing. It seems to create the content however, it is throwing Wordpress errors as well.

![screen shot 2016-07-21 at 2 40 06 pm](https://cloud.githubusercontent.com/assets/19787807/17011439/825f6ada-4f51-11e6-8872-01faa7b0eb6b.png)
![screen shot 2016-07-21 at 2 40 26 pm](https://cloud.githubusercontent.com/assets/19787807/17011437/825e3c82-4f51-11e6-9661-350f34d84077.png)
![screen shot 2016-07-21 at 2 41 25 pm](https://cloud.githubusercontent.com/assets/19787807/17011438/825f0d88-4f51-11e6-808d-9950775f8c2d.png)

Please do let me know if you need me to update the code or send you a snippet.

Thanks,

**Comment by philipjohn** [comment]
> wp_get_sites() is deprecates since version 4.6.0!

I'm going to leave this one for now, as the alternative, `get_sites()` isn't well documented yet.

#15 fixes the rest

**Comment by spacedmonkey** [comment]
wp_get_sites is deprecates in 4.6.0 and the internals of wp_get_sites are now get_sites(). If you have any questions about get_sites, let me know, I wrote it 😄

**Comment by philipjohn** [comment]
:boom: nice one @spacedmonkey - I'll open a new issue for it so I don't forget
